### ISSUE TITLE
Plugin Development Instructions

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/HamsterEcoHelper#1]
## Prerequisites

We got players just like hamster. They collect huge amount of items, weapons, armors, and make them millionaires. However, it seems those players neither sold cheap items to new players, nor spend money on anything else.

Actually I don't think too much death penalty or high teleportation fee is a good idea to prevent inflation. My aim is to simply add more fun to economy system, not making the game harder to play.
## Plugin functions
- Customizing a item list, every item including:
  - item id
  - amount
  - name
  - enchants, lore, and more - to integrate with RPGItems and other looting plugins
  - unit price (player could offer partial amount for a request)
  - available for requisition, `true` or `false`
    - requisition availability/weight, set to 0 to disable this item (0 - 1)
    - requisition timeout in seconds
  - available for auction, `true` or `false`
    - auction minimum sale unit price
    - auction availability/weight, set to 0 to disable this item (0 - 1)
    - auction timeout in seconds
- System market and world shop
  - Player command `/heh offer [unit price]` to offer the item(s) in hand with unit price `[unit price]`
  - Remove the item(s) from player hand, and save both item and offer to database
  - Broadcast the offer in game, and broadcast a message to inform online players that sales offer available, by a fixed interval in seconds
  - Player command `/heh view` to open a chest interface to view available offered items, and unit price in tooltip. Single click to purchase one of this items, and shift-click to purchase the whole slot (Something like SignChestShop plugin).
- System requisition
  - Select an item from list that available for requisition
  - Broadcast the requisite in game, by a fixed or random interval in seconds, with the item details, use `tellraw` in chat window to let players view item details with cursor hover on item name
  - Player hold the requested item(s) in hand, and type `/heh sell`
  - Remove the item(s) from player hand and save to database, then add corresponding money to player account
  - Broadcast a message with the requisition update, request accomplished or how many items still in need, or the requisition has ended when timeout, etc
- System auction
  - Select an item from list that available for auction
  - Broadcast the auction available in game, starting from `minimum sale unit price`, by a fixed or random interval in seconds, with the item details, use `tellraw` as well
  - Player command `/heh bid [unit price]` to place new bid for this auction, bid can be placed multiple times with different price offer. When placing bid, check if player has enough money for bid and return error message if the player does not have enough money or offered price lower than minimum sale unit price and currently highest bid
  - On timeout, the highest bid player wins, remove corresponding money from player account and add the item into player's inventory. (Maybe drop the item in front of the player if player's inventory is full?)
## Other configuration
- Amount of offer slots limit per player group
- Ability to issue a auction in console
- Add auction item by admin in game, admin command `/heh addauction [minimum unit price] [weight] [timeout]` to add item in hand to auction list
- Add requisition item by admin in game, admin command `/heh addrequisition [unit price] [weight]` to add item in hand to requisition list
## Permission node
- `heh.user`
  - `heh.offer`
  - `heh.view`
  - `heh.sell`
  - `heh.bid`
- `heh.admin`
  - `heh.user`
  - `heh.addauction`
  - `heh.addrequisition`

**Comment by phoenixlzx** [comment]
Any idea?
@RecursiveG @cyilin @Taiterio

**Comment by RecursiveG** [comment]
Any advantages in writing own plugin, instead of using [existing ones](https://www.spigotmc.org/search/15358559/?q=auction&t=resource_update&o=date&c[is_resource]=1)?

**Comment by Taiterio** [comment]
Something that I would find extremely interesting for an auction plugin is the visual representation of the market. Like say you build marketplaces that show the item up on a stage, with the name + lore shown above it using named invisible armorstands. 

Personally I think going more for an RP-like approach, as it's something I haven't seen yet on servers and think would make the whole marketing system attractive for RP type scenarios. Players that already have everything in terms of materials can't really profit from any payment/exp for trading, so adding things like titles for experienced traders could give them more incentive to use the market :D

**Comment by phoenixlzx** [comment]
@RecursiveG What we need is a simple and integrated plugin, not install a bunch of plugins and use only few functions of them. Also existed ones are not easy to customize for some needs in our environment.

@Taiterio Nice, but maybe hard to implement, or represent the items.
Actually the use case of this plugin, is when players are playing him/herself or with others, and then take part in the auction/market wherever they are. This is an assistance plugin and will not be performed on a big stage.

But the idea is excellent, however.

**Comment by cyilin** [comment]
I already implement show the item in chat window (7ab7c09)

**Comment by RecursiveG** [comment]
What's the purpose of the `item list`? Are players only allowed to offer or require items which are defined in that list? 
What's the `auction weight`?

**Comment by phoenixlzx** [comment]
@RecursiveG To make it clear,

Item list is the list of items predefined for unlimited stock of system requisition or auction, auction weight is the possibility to be chosen of an item every time, e.g., a legendary item has smaller weight, or possibility to be chosen than a common item every time the auction occur.

Players are only allowed to offer the item every time specified in system requisition. System requisition choose an item in this list. Player could offer anything to world market, so that other players could view and order items from world market.

BTW The user auction you mentioned, how to keep the item when it is in auction?
- Keep with player, player may consume the item when auction.
- Keep in database and remove from player inventory, what about player disconnected and the auction is still going on? modify player inventory directly?

Also we need language & color code support, to customize messages.

**Comment by RecursiveG** [comment]
Open a new issue if you have more requests.
