### ISSUE TITLE
玩家征购和拍卖

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/HamsterEcoHelper#10]
感觉是呼声相对比较高的功能。
### 玩家征购
- 命令 `/heh req [item] [unit price] [amount]` 或者 `/heh req hand [unit price] [amount]` 以 `unit price` 单价征购 `amount` 数量的 `item` 或者手中的物品。
- 玩家的背包必须有足够数量(如果物品可堆叠则计算堆叠后占用)的空间。
- 玩家的账户余额必须大于或等于 `unitprice * amount`
- 征购的物品必须全部 `EXACT MATCH` 且可以在配置文件中设置征购有效时长和每个玩家的征购冷却时间。

玩家 A 启动征购后，将需要的金钱从玩家 A 账户中扣除并暂存到系统，有其他玩家售出物品则从该部分金钱中支付相应的额度给玩家 A，物品则直接放入征购玩家的背包。征购完成/超时后移除征购锁并记录时间以便计算冷却时间。如果征购数量未完成，则剩余的金钱退回玩家 A 的账户。
### 玩家竞拍
- 命令 `/heh auc [base price] [step price] [reserve price|optional]` 以 `base price` 起步价、`step price` 为步进价竞拍手中的物品。如果玩家设置了 `reserve price`，则在未满足 `reserve price` 时竞拍超时判为流拍。
- 配置文件中可设置玩家竞拍的超时、每个玩家的竞拍冷却时间和 commission fee %。

玩家 A 启动竞拍后，将手中的物品暂存到系统。如竞拍成功且配置文件中 commission fee 设置为 5%，将从胜出玩家账户中扣除其出价，出价的 95% 支付给玩家 A 的账户并将物品交付给胜出玩家。如流拍，物品将退回玩家 A 的背包。

玩家征购和竞拍消息与系统征购和竞拍一样，所有的征购/竞拍互斥，不会同时出现两个征购/竞拍活动。且启动征购/竞拍的玩家不能参加自己启动的活动。

权限 `heh.userreq` 和 `heh.userauc` 默认为玩家

**Comment by RecursiveG** [comment]
implemented e2e90918b7f92416d821c10014420404a521d2f0
