### ISSUE TITLE
系统 balance 的一些修改

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/HamsterEcoHelper#19]
由插件修改的数值全部单独保存到配置文件 `variables.txt`，不使用 yaml 是因为不需要过于复杂的解析，不过用 yaml 也可以。

配置文件大概这样

```
balance: 10000.0
market_placement_fee_timestamp: 1485537852609
```

其他逻辑上的修改：

* 市场中的税收取后保存到 `balance`，
* placement fee 收取后保存到 `balance` 
* 玩家拍卖收取的 auction fee 保存到 `balance`

新增：

暴露一个 API，可允许其他插件调用来修改 `balance`

**Comment by cyilin** [comment]
还是继续用yaml了，数据储存在 variables.yml 中
