### ISSUE TITLE
demo 版的一些问题

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/HamsterEcoHelper#2]
- [x] 竞拍价格更新时可以做成全局公告，以便其他玩家出价加入
- [x] 系统征购的物品名称还需要改善，目前骨粉会显示为 `INK_SACK`。另外也希望征购物品可以用 `tellraw`
- [x] 系统征购到一批物品后可以公告目前的进度更新
- [x] 世界商店新增 offer 时的公告消息似乎有问题
- [x] 普通玩家默认没有权限 make offer，或者权限节点配置有问题
- [x] 世界商店里物品的 Price 可以改为显示 Unit Price
- [x] 尽快完善语言和自定义消息支持
- [x] 系统征购和竞拍的 interval 改为 `base_interval + random(0, i)` 的形式
- [x] 系统征购/竞拍等，可以在 console 里留下一些日志方便管理
- [x] ~~消息输出的自定义 prefix 支持~~ 暂时由语言文件代替

其他问题等待玩家反馈。

**Comment by cyilin** [comment]
不能offer的问题可能是没有可用的slot，比如配置文件中的"default"组，需要给予heh.offer.default权限

**Comment by phoenixlzx** [comment]
@RecursiveG 说的打算改变世界商店的数据库格式是怎么打算的？

**Comment by RecursiveG** [comment]
@cyilin 
现在世界商店的数据库是手工拼接SQL的
可以考虑使用bukkit自带的数据库系统。
参考[utils.Database 类](https://github.com/NyaaCat/HamsterEcoHelper/blob/master/src/main/java/cat/nyaa/HamsterEcoHelper/utils/Database.java#L104)

**Comment by RecursiveG** [comment]
@cyilin 
另外配置文件的读取请考虑在[Configuration类](https://github.com/NyaaCat/HamsterEcoHelper/blob/master/src/main/java/cat/nyaa/HamsterEcoHelper/Configuration.java)中统一做

**Comment by phoenixlzx** [comment]
自定义消息可以用 formatting code 么？支持 `&` 转义么？

**Comment by RecursiveG** [comment]
@phoenixlzx 可以的

**Comment by phoenixlzx** [comment]
@felixonmars 来开一下 CI 吧，就不用每次都手动 build 了。
