### ISSUE TITLE
整合 SCS

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/HamsterEcoHelper#23]
我们不需要其他的商店插件了，因此可以把 SCS 的功能整合进来。

+ 另外添加一个 lotto machine 的功能

## 配置文件

```
signshop:
  sign_limit:
    default: 2
    advanced: 3
  slot_limit:
    default: 16
    advanced: 18
  tax: 5
```

即：

* 默认玩家组可以放置最多 2 个牌子（销售+收购），而 `advanced` 组可以放置 3 个。
* 默认玩家组可以使用 16 个槽（销售+收购），而 `advanced` 组可以使用 18 个。
* lotto machine 不计算 slot 数量（不受限制，也不影响玩家的 slot），但是受 sign 数量的限制，也就是每个 lotto machine 的牌子会占用一个牌子数量。
* 每次交易税率为 5%，如果设置为 0 则禁用。
* 收取的税款保存到系统 balance。

## 木牌逻辑

1. 一个玩家会有两个木牌，销售和收购。也就是，一个玩家创建的所有同类型的木牌，内容都是一样的。
2. 销售木牌类似 Global Market 的逻辑，一个可以翻页的箱子界面展示所有的商品和价格信息。左键点击购买 1 个，shift+左键购买整个 slot。
3. 收购木牌类似 signshop 的逻辑，定义一个用于存放物品的箱子，通过拿着特定物品右键点击木牌将物品售出，shift+右键点击出售手中的全部（或可能收购的最大值）。
4. lotto 木牌即抽奖，定义一个保存奖品的箱子，玩家点击木牌时支付一定金钱获得箱子中随机一个 slot 的物品。当箱子为空时停止交易（点击显示缺货）

### 销售物品

1. 使用 `/heh shop sell [unit price]` 将手中的物品以 `unit price` 保存到商店存储
2. 木牌格式：
  * 第一行 `[shop]`
  * 第二行 `sell`
  * 第三行 任意描述文本
  * 第四行 任意描述文本

玩家右键点击该木牌，即可通过类似 Global Market 的界面购买商品。

### 出售物品

1. `/heh shop storage [set|info]` 设置/覆盖/查看物品存储箱的信息
2. `/heh shop buy [unit price]` 将手中的物品信息以 `unit price` 保存到收购列表（不移除手上的物品）
3. 木牌格式：
  * 第一行 `[shop]`
  * 第二行 `buy`
  * 第三行 任意描述文本
  * 第四行 任意描述文本

玩家空手或使用其他物品右键点击该木牌，即可获得该商店收购的物品列表和收购单价，光标移动到文本可以看到物品详细信息。

将收购的物品拿在手上右键点击木牌即可将物品售出，shift+右键将手中的物品全部售出，或售出最大可能的数量。

### Lotto

1. `/heh shop lotto [set|info]` 设置/覆盖/查看 Lotto 存储箱的信息
2. 木牌格式
  * 第一行 `[shop]`
  * 第二行 `lotto`
  * 第三行 任意描述文本
  * 第四行 每次交易单价

**Comment by phoenixlzx** [comment]
添加了 lotto 木牌，不需要红石制作抽奖机。

**Comment by cyilin** [comment]
玩家向商店出售物品的操作改成了左键点击告示牌 (右键可能触发ce或rpgitem的使用)

**Comment by phoenixlzx** [comment]
GJ.
