### ISSUE TITLE
Can't load death_penalty.worlds configulation

### ISSUE THREAD

**Issue by lwl12** [NyaaCat/HamsterEcoHelper#33]
> https://github.com/NyaaCat/HamsterEcoHelper/blob/master/src/main/java/cat/nyaa/HamsterEcoHelper/Configuration.java#L63

当该行 ArrayList 不添加类型 String 时, 无法正确的从配置文件中加载设置（重载后自动清回 []）
修改后为 ``` public List<String> death_penalty_worlds = new ArrayList<String>();```

卷表示不加用的也好好的，所以不知道具体是 BUG 还是什么奇怪的环境问题？
本地环境如下：
>openjdk version "1.8.0_131"
>OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.2-b11)
>OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by Librazy** [comment]
Java运行时是类型擦除的，而且这里的 `new ArrayList<>()` 也会自动推断出泛型参数才对……？

不过从 `ArrayList<String>` 读到 `Integer` 我也是遇到过的……

**Comment by lwl12** [comment]
所以大概只能解释为玄学了（？）毕竟不加就读不出来

**Comment by cyilin** [comment]
这里不该有什么问题啊，是不是格式写错了。。。配置文件写法大概是这样的：
death_penalty:
  worlds:
  - world
  - world_nether

**Comment by lwl12** [comment]
@cyilin 唔，就是这样写的，然后不加 String 的话就被重置成 [] 了……
加这个是从 NyaaUtils 源码里发现的 - -

**Comment by lwl12** [comment]
于是我把 String 删了再次编译了一遍……
神奇的事情发生了，这次不清了……
我可以 100% 确认之前被清的时候格式没错（毕竟换着法子上了十几次
大概这就是玄学吧……
