### ISSUE TITLE
您好，在安装和使用该插件的过程中出现了报错

### ISSUE THREAD

**Issue by LittleStarsQAQ** [NyaaCat/HamsterEcoHelper#43]
尊敬的开发者：
        您好！
        非常感谢您开发出如此优秀的插件，也期待这款插件可以得到更好的发展！在安装和使用这款插件的过程中，有几个问题想向您请教一下：
        1、在启动服务器时，插件会有以下报错：
![default](https://user-images.githubusercontent.com/34884072/41727967-46ce8904-75a8-11e8-88f0-b7e66af7cd3c.png)
        2、在游戏内使用该插件时（比如创建出售商店），插件会有以下报错：
![default](https://user-images.githubusercontent.com/34884072/41728410-5cee81ac-75a9-11e8-9205-d605c505e926.png)

在进行插件测试时使用的服务器端为spigot-1.12.2（尝试过在spigot-1.12下运行，同样报错），使用插件如下：
1、EssentialsX-2.15.0.1
2、EssentialsXAntiBuild-2.15.0.1
3、EssentialsXChat-2.15.0.1
4、EssentialsXGeoIP-2.15.0.1
5、EssentialsXProtect-2.15.0.1
6、EssentialsXSpawn-2.15.0.1
7、HamsterEcoHelper-master-v3.136
8、LangUtils-1.9
9、NyaaCore-v5.0.162-mc1.12
10、NyaaUtils-v4.0.190-mc1.12
11、Vault-1.6.6
12、worldedit-bukkit-6.1.7.3
详细服务器运行日志：
[latest.log](https://github.com/NyaaCat/HamsterEcoHelper/files/2124291/latest.log)
服务器运行环境：Windows
        
        请问如何消除或解决以上报错？真诚的期待与感谢您的答复！

此致
敬礼

**Comment by lwl12** [comment]
现在 HEH 好像是配合 NyaaCore 4.x 使用的吧，可以降级 NC 试试？

**Comment by Librazy** [comment]
请使用NyaaCore 4.x。抱歉由于预期外的原因NyaaCore 5的适配尚未完成，预计届时将统一所有NyaaCore系列插件的大版本号，请在安装时使用相同大版本号的插件。

NyaaCore 4.1 最新版本
https://github.com/NyaaCat/NyaaCore/releases/tag/v4.1.163-mc1.12
