### ISSUE TITLE
颜色代码显示问题

### ISSUE THREAD

**Issue by Ghost-chu** [NyaaCat/HamsterEcoHelper#47]
按住shift右键点击牌子 牌子的颜色代码会变成这样
![https://miao.su/images/2018/08/16/TIM201808161943462c866.png](https://miao.su/images/2018/08/16/TIM201808161943462c866.png)

**Comment by Ghost-chu** [comment]
https://miao.su/images/2018/08/16/TIM201808161943462c866.png

**Comment by cyilin** [comment]
heh中没有shift+右键更新告示牌的功能，应该是其他插件的问题。
