### ISSUE TITLE
Feature Request: Stop running specific cmds during auction

### ISSUE THREAD

**Issue by Akiranya** [NyaaCat/HamsterEcoHelper#52]
Hello.

Can you add a feature that stops players from running specific cmds during auction? To be more precise, players who start or bid on an auction should not be able to use the cmds specified in config until it ends.

This feature can be very useful in certain circumstance because it would make HEH more compatible with other plugins. Let me show a real example :)

For current version of HEH, if a player starts an auction, the item he sells will be taken out from his inventory then. After that, the item will either return to his inventory, or be sent to buyer's inventory. Seems works fine.

Ok, what if a server has a fancy minigame installed where players should only be able to use predefined items to play with? The answer is, using auction, players can take his own items into the minigame since they can start an auction in extremely high price (which is impossible to achive a trade), then they immediately join the minigame. Due to the fact that the auction is really expensive, the auction item will defintely return to their inventory when auction ends, therefore they can use their own 'imbalanced' items in the minigame to fight against other players, which is not expected.

Well, if they were stopped from using cmds to join the minigame during auction, lifes would be much easier ヾ(◍°∇°◍)ﾉﾞ

Would be very appreciated if this feature could be added!

Thank you very much.

Happy new year! :D
Best wishes

**Comment by phoenixlzx** [comment]
This should be guarded by the server rules, not by plugin.

I don't see any point to implement this specific feature.

**Comment by Akiranya** [comment]
Yes what you said kind of makes sense, but not everyone would follow the server rules. That was why I opened this issue. Sometimes servers really need enforcement rules implemented by plugins, not by our minds.

Alternatively, there could be an API for developers who would like to have access to control auction process in order for HEH to be compatible with as more other plugins as possible.
