### ISSUE TITLE
如何使用MySQL数据库

### ISSUE THREAD

**Issue by LittleStarsQAQ** [NyaaCat/HamsterEcoHelper#53]
![image](https://user-images.githubusercontent.com/34884072/53295848-2c5e8d80-383f-11e9-9924-4e3c7a897944.png)
如果使用MySQL，应该怎么修改？

**Comment by Librazy** [comment]
https://github.com/NyaaCat/NyaaCore/issues/26#issuecomment-362337684

database:
  provider: mysql
  connection:
    autoscan: true
    url: jdbc:MySQL://localhost:3306/heh
    username: username
    password: password
