### ISSUE TITLE
1.12.2 "Command Executed!" does not apply locale or even in en_US

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [NyaaCat/HamsterEcoHelper#62]
I'm forging my own minecraft server and choose to /heh like the good old days.  
The plugin works in most case and after every command send in chat or console,  
plugin will report "Command Executed!" back to player or console.

I fount the translate in `en_US.yml` or `zh_CN.yml`,
```
user:
    info:
        command_complete: Command Executed!
```
Set "zh_CN" in `config.yml`, the plugin still report  
"Command Executed!" instead of "命令已执行！" written in `zh_CN.yml`.

Modifying `en_US.yml` and use en_US locale,  
the changes in `en_US.yml` about `command_complete` will not work.

Using
```
HamsterEcoHelper-master-v3.136
NyaaCore-v4.1.72-mc1.12
LangUtils-1.9
```
Described in spigot resource page.  
Actually I'm not quite sure about what version should be used in Minecraft 1.12.2,  
There is tons of release in CI or github release, are 1.13 or up to 1.15.  
1.12.2 version is seems not officially supported but the days I'm still play in Nyaa,  
there is Minecraft 1.12.2 and /heh out there.

**Comment by RecursiveG** [comment]
I think that message is actually provided by NyaaCore ([src](https://github.com/NyaaCat/NyaaCore/blob/1.16/src/main/resources/lang/en_US.yml#L4)). Check [this](https://github.com/NyaaCat/NyaaCore/wiki/LanguageRepository.java) and read the `Internal Section & Normal Section` chapter.
Try putting it under `internal`:
```
internal:
    info:
        command_complete: "Your message here"
```

**Comment by mhtvsSFrpHdE** [comment]
@RecursiveG I got the direction, thank you!
