### ISSUE TITLE
无法向全球商店中上架物品

### ISSUE THREAD

**Issue by Neveark** [NyaaCat/HamsterEcoHelper#63]
服务端版本:Spigot 1.15.2，Paper 1.15.2，都出现了同样的问题
NyaaCore版本:7.1.350，7.1.360，7.1.362

报错如下：
> [01:11:32] [Server thread/INFO]: KagehiraNE issued server command: /heh market offer 122
> [01:11:32] [Server thread/WARN]: java.lang.RuntimeException: INSERT INTO market(amount,id,item,player_id,unit_price) VALUES(?,?,?,?,?)
{amount=1, item=eJwFwcEJgDAMBdBfRejZARzEqxe3KKFGCaUJtFFwMefzvQBgH7HoS5StcRLn2p1ySQc5Pdy6mALxixjkwFxFOTc6fTUqqculAdNmt3rAD5MpF9U=, player_id=59d9ab89-e318-42ca-b786-2bfa18d29af9, id=null, unit_price=122.0}
> [01:11:32] [Server thread/WARN]: at cat.nyaa.nyaacore.orm.backends.BaseTypedTable.insert(BaseTypedTable.java:62)
> [01:11:32] [Server thread/WARN]: at cat.nyaa.nyaacore.orm.backends.SQLiteDatabase$SQLiteTypedTable.insert(SQLiteDatabase.java:191)
> [01:11:32] [Server thread/WARN]: at cat.nyaa.HamsterEcoHelper.database.Database.marketOffer(Database.java:125)
> [01:11:32] [Server thread/WARN]: at cat.nyaa.HamsterEcoHelper.market.MarketManager.offer(MarketManager.java:90)
> [01:11:32] [Server thread/WARN]: at cat.nyaa.HamsterEcoHelper.market.MarketCommands.offer(MarketCommands.java:42)
> [01:11:32] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [01:11:32] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [01:11:32] [Server thread/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [01:11:32] [Server thread/WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [01:11:32] [Server thread/WARN]: at cat.nyaa.nyaacore.cmdreceiver.CommandReceiver$SubCommandInfo.callCommand(CommandReceiver.java:78)
> [01:11:32] [Server thread/WARN]: at cat.nyaa.nyaacore.cmdreceiver.CommandReceiver.acceptCommand(CommandReceiver.java:325)
> [01:11:32] [Server thread/WARN]: at cat.nyaa.nyaacore.cmdreceiver.CommandReceiver$SubCommandInfo.callCommand(CommandReceiver.java:76)
> [01:11:32] [Server thread/WARN]: at cat.nyaa.nyaacore.cmdreceiver.CommandReceiver.acceptCommand(CommandReceiver.java:325)
> [01:11:32] [Server thread/WARN]: at cat.nyaa.nyaacore.cmdreceiver.CommandReceiver.onCommand(CommandReceiver.java:296)
> [01:11:32] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
> [01:11:32] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
> [01:11:32] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723)
> [01:11:32] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1658)
> [01:11:32] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1498)
> [01:11:32] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
> [01:11:32] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
> [01:11:32] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
> [01:11:32] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
> [01:11:32] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
> [01:11:32] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
> [01:11:32] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
> [01:11:32] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)
> [01:11:32] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)
> [01:11:32] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
> [01:11:32] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895)
> [01:11:32] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)
> [01:11:32] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
> [01:11:32] [Server thread/WARN]: Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT] Abort due to constraint violation (NOT NULL constraint failed: market.id)
> [01:11:32] [Server thread/WARN]: at org.sqlite.core.DB.newSQLException(DB.java:941)
> [01:11:32] [Server thread/WARN]: at org.sqlite.core.DB.newSQLException(DB.java:953)
> [01:11:32] [Server thread/WARN]: at org.sqlite.core.DB.execute(DB.java:854)
> [01:11:32] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:56)
> [01:11:32] [Server thread/WARN]: at cat.nyaa.nyaacore.orm.backends.BaseTypedTable.insert(BaseTypedTable.java:60)
> [01:11:32] [Server thread/WARN]: ... 31 more

**Comment by ReinWD** [comment]
fixed
