### ISSUE TITLE
希望增加个信息的屏蔽/开启指令

### ISSUE THREAD

**Issue by miu-wen** [NyaaCat/HamsterEcoHelper#7]
如题，增加一个信息的屏蔽/开启指令，并不是所有人都喜欢拍卖或者征购刷版。。。打了屏蔽指令的人不会在聊天框里刷出这些信息。。。

**Comment by cyilin** [comment]
已添加命令 `/heh mute` 和 `/heh unmute`  (使用权限 `heh.mute` 已经默认包括在 `heh.user` 中)

直到服务器重启前都不再接收广播消息，服务器重启后需要自己重新用命令屏蔽一下 (咱觉得没必要永久屏蔽吧...)

**Comment by phoenixlzx** [comment]
（悄悄说
其实 mute 和 unmute 比较合适一点。

**Comment by cyilin** [comment]
@phoenixlzx 已经改了
