### ISSUE TITLE
征购广播没有正确消除

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/HamsterEcoHelper#9]
一些物品已经没有在征购了仍然出现广播导致玩家误以为还在征购。

一般发生于 requisition internal 设置得比较低的时候。

**Comment by cyilin** [comment]
目前测试的话，当前征购没结束时有可能触发出第二个征购，导致同时有两个征购的广播消息，但没找到第二个征购能成功执行的原因。。

**Comment by RecursiveG** [comment]
fixed fd5e94ba9f7f7775fb84c8cd3be778ddcd7036ce
